import{S as h,a as b,i as y}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const L=document.querySelector(".form"),i=document.querySelector(".gallery"),f=document.querySelector(".load-more"),w=document.querySelector(".loader"),F="https://pixabay.com/api/?",g="41838849-75d2e43a80bdb544c2e4afc3a",v={key:g,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};let l=1,n="";const S=new h(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}),d=e=>{w.style.display=e?"block":"none"},u=e=>{f.style.display=e?"block":"none"},x=e=>{const r=e.map(o=>`
        <li class="gallery-item">
          <a href=${o.largeImageURL}>
            <img class="gallery-img" src=${o.webformatURL} alt=${o.tags}/>
          </a>
          <div class="gallery-text-box">
            <p>Likes: <span class="text-value">${o.likes}</span></p>
            <p>Views: <span class="text-value">${o.views}</span></p>
            <p>Comments: <span class="text-value">${o.comments}</span></p>
            <p>Downloads: <span class="text-value">${o.downloads}</span></p>
          </div>
        </li>
      `);i.insertAdjacentHTML("beforeend",r.join("")),S.refresh()};L.addEventListener("submit",async e=>{if(e.preventDefault(),d(!0),n=encodeURIComponent(e.target.elements.search.value.trim()),n===""){console.error("Please enter a valid search query.");return}l=1;try{await m(n,l)}catch(r){console.error(r.message)}finally{d(!1)}e.target.reset()});f.addEventListener("click",async()=>{u(!1),l++;try{await m(n,l)}catch(e){console.error(e.message)}finally{d(!1)}});const C=()=>{const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0},q=()=>{C()>0||console.warn("Gallery card not found. Sorry, you can`t scroll.")},p=()=>{y.info({position:"topRight",messageColor:"#FFFFFF",backgroundColor:"#36B3D9",titleSize:"8px",closeOnEscape:!0,message:"We're sorry, but you've reached the end of search results."})},m=async(e,r)=>{const o=await b.get(F,{params:{q:e,page:r,per_page:v.per_page,key:g}}),{hits:a,totalHits:t}=o.data;!a||a.length===0?r===1?y.error({position:"topRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Sorry, there are no images matching your search query. Please try again!"}):p():(r===1&&(i.innerHTML=""),x(a),t&&i.childElementCount>=t?(u(!1),p()):(u(!0),q()))};
//# sourceMappingURL=commonHelpers.js.map
